#include<conio.h>
#include<cstdio>
#include<iostream>
#include<string.h>
#include<cstdlib>
usingnamespacestd;
staticintp=0;
classa
{
charbusn[5],driver[10],arrival[5],depart[5],from[10],to[10],seat[8][4][10];
public:
voidinstall();
voidallotment();
voidempty();
voidshow();
voidavail();
voidposition(inti);
}
bus[10];
voidvline(charch)
{
for(inti=80;i>0;i--)
cout<<ch;
}
voida::install()
{
cout<<"Enterbusno:";
cin>>bus[p].busn;
cout<<"\nEnterDriver'sname:";
cin>>bus[p].driver;
cout<<"\nArrivaltime:";
cin>>bus[p].arrival;
cout<<"\nDeparture:";
cin>>bus[p].depart;
cout<<"\nFrom:\t\t\t";
cin>>bus[p].from;
cout<<"\nTo:\t\t\t";
cin>>bus[p].to;
bus[p].empty();
p++;
}
voida::allotment()
{
intseat;
charnumber[5];
top:
cout<<"Busno:";
cin>>number;
intn;
for(n=0;n<=p;n++)
{
if(strcmp(bus[n].busn,number)==0)
break;
}
while(n<=p)
{
cout<<"\nSeatNumber:";
cin>>seat;
if(seat>32)
{
cout<<"\nThereareonly32seatsavailableinthisbus.";
}
else
{
if(strcmp(bus[n].seat[seat/4][(seat%4)-1],"Empty")==0)
{
cout<<"Enterpassanger'sname:";
cin>>bus[n].seat[seat/4][(seat%4)-1];
break;
}
else
cout<<"Theseatno.isalreadyreserved.\n";
}
}
if(n>p)
{
cout<<"Entercorrectbusno.\n";
gototop;
}
}
voida::empty()
{
for(inti=0;i<8;i++)
{
for(intj=0;j<4;j++)
{
strcpy(bus[p].seat[i][j],"Empty");
}
}
}
voida::show()
{
intn;
charnumber[5];
cout<<"Enterbusno:";
cin>>number;
for(n=0;n<=p;n++)
{
if(strcmp(bus[n].busn,number)==0)
break;
}
while(n<=p)
{
vline('*');
cout<<"Busno:\t"<<bus[n].busn
<<"\nDriver:\t"<<bus[n].driver<<"\t\tArrivaltime:\t"
<<bus[n].arrival<<"\tDeparturetime:"<<bus[n].depart
<<"\nFrom:\t\t"<<bus[n].from<<"\t\tTo:\t\t"<<
bus[n].to<<"\n";
vline('*');
bus[0].position(n);
inta=1;
for(inti=0;i<8;i++)
{
for(intj=0;j<4;j++)
{
a++;
if(strcmp(bus[n].seat[i][j],"Empty")!=0)
cout<<"\nTheseatno"<<(a-1)<<"isreservedfor"<<bus[n].seat[i][j]<<".";
}
}
break;
}
if(n>p)
cout<<"Entercorrectbusno:";
}
voida::position(intl)
{
ints=0;p=0;
for(inti=0;i<8;i++)
{
cout<<"\n";
for(intj=0;j<4;j++)
{
s++;
if(strcmp(bus[l].seat[i][j],"Empty")==0)
{
cout.width(5);
cout.fill('');
cout<<s<<".";
cout.width(10);
cout.fill('');
cout<<bus[l].seat[i][j];
p++;
}
else
{
cout.width(5);
cout.fill('');
cout<<s<<".";
cout.width(10);
cout.fill('');
cout<<bus[l].seat[i][j];
}
}
}
cout<<"\n\nThereare"<<p<<"seatsemptyinBusNo:"<<bus[l].busn;
}
voida::avail()
{
for(intn=0;n<p;n++)
{
vline('*');
cout<<"Busno:\t"<<bus[n].busn<<"\nDriver:\t"<<bus[n].driver
<<"\t\tArrivaltime:\t"<<bus[n].arrival<<"\tDepartureTime:\t"
<<bus[n].depart<<"\nFrom:\t\t"<<bus[n].from<<"\t\tTo:\t\t\t"
<<bus[n].to<<"\n";
vline('*');
vline('_');
}
}
int main()
{
system("cls");
int w;
while(1)
{
//system("cls");
cout<<"\n\n";
cout<<"\t\t***SIMPLEBUSRESERVATIONSYSTEM***";
cout<<"\n\n";
cout<<"\t\t\t1.Install\n\t\t\t"
<<"2.Reservation\n\t\t\t"
<<"3.Show\n\t\t\t"
<<"4.BusesAvailable\n\t\t\t"
<<"5.Exit";
cout<<"\n\t\t\tEnteryourchoice:-";
cin>>w;
switch(w)
{
case1: bus[p].install();
break;
case2: bus[p].allotment();
break;
case3: bus[0].show();
break;
case4: bus[0].avail();
break;
case5: exit(0);
}
}
return0;
}